spring:
  application:
    name: aye-modulo-api

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8020

feign:
  client:
    config:
      default:
        connectTimeout: 300000
        readTimeOut: 300000
